# architecture
arch: vit_base
enc_arch: MAEViTEncoder
dec_arch: MAEViTDecoder

# wandb
proj_name: mae
run_name: ${proj_name}_${arch}_${dataset}
wandb_id:

# dataset
dataset: im100
data_path: /data/add_disk0/leizhou/imagenet100/images
tr_listfile: /nfs/bigcornea/add_disk0/leizhou/imagenet100/sorted_train_list.txt
va_listfile: /nfs/bigcornea/add_disk0/leizhou/imagenet100/sorted_val_list.txt

# output
output_dir: /nfs/bigdisk/leizhou/ssl-v2/${run_name}
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
mean_std_type: IMN
crop_min: 0.08

# trainer
trainer_name: MAETrainer
lr: 1.5e-4
batch_size: 256
vis_batch_size: 4
start_epoch: 0
warmup_epochs: 40
epochs: 800
workers: 32
resume:

# model
patchembed: 'PatchEmbed'
mask_ratio: 0.75
input_size: 224
patch_size: 16
in_chans: 3
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
decoder_embed_dim: 256
decoder_depth: 8
decoder_num_heads: 8
fourier_embed_dim: 24
fourier_temperature: 0.01

# optimizer
type: adamw
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# logging
vis_freq: 10000000
save_freq: 40
print_freq: 20

# distributed processing
gpu: 0
dist_url: #'tcp://localhost:10004'
world_size: 1
multiprocessing_distributed: false
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node:

# randomness
seed:

# debugging
debug: false